const CAPI=`${location.origin}/api`;const cToken=()=>localStorage.customerToken;
async function cRequest(path,options={}){const r=await fetch(CAPI+path,{...options,headers:{'Content-Type':'application/json',...(cToken()&&{Authorization:`Bearer ${cToken()}`}),...options.headers}});const body=await r.json();if(!r.ok)throw new Error(body.message||'Request failed');return body.data}
function showError(message){const el=document.querySelector('.error');if(el)el.textContent=message}
async function customerLogin(e){e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));const data=await cRequest('/auth/login',{method:'POST',body:JSON.stringify({...f,role:'customer'})});localStorage.customerToken=data.token;location.href='customer-home.html'}catch(e){showError(e.message)}}
async function customerRegister(e){e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));await cRequest('/auth/register/customer',{method:'POST',body:JSON.stringify(f)});document.querySelector('#login-phone').value=f.phone;showError('Account created. Sign in now.')}catch(e){showError(e.message)}}
function customerLogout(){localStorage.removeItem('customerToken');location.href='customer-login.html'}
const placeholder='https://placehold.co/600x400/e1f4e8/15945a?text=FreshLane';
const shopPhotos={supermarket:'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80',vegetables:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',bakery:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',fish:'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=800&q=80',meat:'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=800&q=80',dairy:'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=800&q=80',other:placeholder};
async function loadCustomerHome(){const params=new URLSearchParams(location.search);if(params.get('shopId'))return loadShopProducts(params.get('shopId'),params.get('name'));const render=(lat=10.8505,lng=76.2711)=>cRequest(`/shops/nearby?latitude=${lat}&longitude=${lng}`).then(shops=>{document.querySelector('#section-title').textContent='Popular shops near you';document.querySelector('#cards').innerHTML=shops.length?shops.map(s=>`<article class="shop-card" onclick="openShop('${s._id}','${encodeURIComponent(s.shopName)}')"><div class="image-wrap"><img class="card-image" src="${shopPhotos[s.shopType]||placeholder}" alt="${s.shopName}"><span class="time-pill">⚡ 20–35 min</span></div><div class="card-body"><span class="badge">${s.shopType}</span><span class="rating">★ 4.8</span><h3>${s.shopName}</h3><p>${s.address||'Fresh local delivery'}</p><strong>Delivers within ${s.deliveryRadiusKm} km →</strong></div></article>`).join(''):'<div class="panel empty">No approved shops found near this location yet.</div>'}).catch(e=>showError(e.message));if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>render(p.coords.latitude,p.coords.longitude),()=>render());else render()}
function openShop(id,name){location.href=`customer-home.html?shopId=${id}&name=${name}`}
async function loadShopProducts(shopId,name){document.querySelector('#section-title').textContent=decodeURIComponent(name||'Products');const products=await cRequest(`/products?shopId=${shopId}`);document.querySelector('#cards').innerHTML=products.length?products.map(p=>`<article class="product-card"><div class="image-wrap"><img class="card-image" src="${p.images?.[0]||placeholder}" alt="${p.name}"><span class="time-pill">${p.unit}</span></div><div class="card-body"><span class="badge">${p.category||'Grocery'}</span><h3>${p.name}</h3><p>${p.description||'Freshly packed by the vendor'}</p><span class="price">₹${p.offerPrice??p.price}</span>${p.offerPrice!=null?`<span class="old-price">₹${p.price}</span>`:''}<p>${p.stockQuantity} ${p.unit} in stock</p><button class="btn" onclick="addCustomerCart('${p._id}',event)">＋ Add to cart</button></div></article>`).join(''):'<div class="panel empty">This shop has no products yet. Check back soon.</div>'}
async function addCustomerCart(productId,event){event.stopPropagation();if(!cToken())return location.href='customer-login.html';try{await cRequest('/cart/items',{method:'POST',body:JSON.stringify({productId,quantity:1})});event.target.textContent='Added ✓'}catch(e){alert(e.message)}}
async function loadCustomerCart(){if(!cToken())return location.href='customer-login.html';try{const data=await cRequest('/cart');const groups=data.shops||[];document.querySelector('#cart-content').innerHTML=groups.length?groups.map(g=>`<section class="panel"><h2>${g.shop?.shopName||'Shop'}</h2>${g.items.map(i=>`<div class="cart-row"><img src="${i.productId?.images?.[0]||placeholder}"><div><strong>${i.productId?.name}</strong><div>${i.quantity} × ₹${i.productId?.offerPrice??i.productId?.price??i.priceAtAddTime}</div></div><strong>₹${((i.productId?.offerPrice??i.productId?.price??i.priceAtAddTime)*i.quantity).toFixed(2)}</strong></div>`).join('')}<h3>Shop subtotal: ₹${g.subtotal.toFixed(2)}</h3></section>`).join('')+'<div class="panel"><button class="btn" onclick="alert(\'Checkout requires Razorpay keys in Render.\')">Continue to checkout</button></div>':'<div class="panel empty">Your cart is empty.</div>'}catch(e){showError(e.message)}}
