const bcrypt=require('bcryptjs');const Shop=require('../models/Shop');const MasterOrder=require('../models/MasterOrder');const VendorSettlement=require('../models/VendorSettlement');const DeliveryPartner=require('../models/DeliveryPartner');const Product=require('../models/Product');const {ok}=require('../utils/responseHandler');
const orders=async(_q,r,n)=>{try{ok(r,await MasterOrder.find().sort({createdAt:-1}).populate('customerId','name phone').populate('subOrderIds'));}catch(e){n(e)}};
const shops=async(_q,r,n)=>{try{ok(r,await Shop.find().sort({createdAt:-1}));}catch(e){n(e)}};
async function shopStatus(req,res,next){try{const s=await Shop.findByIdAndUpdate(req.params.shopId,{status:req.body.status},{new:true,runValidators:true});ok(res,s);}catch(e){next(e)}}
async function commission(req,res,next){try{const s=await Shop.findByIdAndUpdate(req.params.shopId,{commissionPercentage:req.body.commissionPercentage},{new:true,runValidators:true});ok(res,s);}catch(e){next(e)}}
const settlements=async(_q,r,n)=>{try{ok(r,await VendorSettlement.find().populate('shopId','shopName').populate('subOrderId'));}catch(e){n(e)}};
async function processSettlements(req,res,next){try{const ids=req.body.settlementIds||[];const result=await VendorSettlement.updateMany({_id:{$in:ids},settlementStatus:'pending'},{$set:{settlementStatus:'processed',settledAt:new Date()}});ok(res,result,'Settlements processed');}catch(e){next(e)}}
const deliveryPartners=async(_q,r,n)=>{try{ok(r,await DeliveryPartner.find().select('-passwordHash'));}catch(e){n(e)}};
const products=async(_q,r,n)=>{try{ok(r,await Product.find().populate('shopId','shopName'));}catch(e){n(e)}};
async function createShop(req,res,next){try{const b=req.body;const password=b.password||'Vendor@123';const passwordHash=await bcrypt.hash(password,12);const shop=await Shop.create({ownerName:b.ownerName,shopName:b.shopName,shopType:b.shopType||'supermarket',phone:b.phone,email:b.email||undefined,passwordHash,location:{latitude:Number(b.latitude),longitude:Number(b.longitude)},address:b.address,deliveryRadiusKm:Number(b.deliveryRadiusKm||5),commissionPercentage:Number(b.commissionPercentage??10),minimumOrderValue:Number(b.minimumOrderValue||0),status:b.status||'approved',isOpen:b.isOpen!==false});ok(res,{shop,credentials:{phone:shop.phone,password}},'Vendor onboarded');}catch(e){next(e)}}
async function createProduct(req,res,next){try{const b=req.body;const product=await Product.create({shopId:b.shopId,name:b.name,category:b.category,description:b.description,price:Number(b.price),offerPrice:b.offerPrice?Number(b.offerPrice):undefined,stockQuantity:Number(b.stockQuantity||0),unit:b.unit||'piece',images:b.imageUrl?[b.imageUrl]:Array.isArray(b.images)?b.images:[],isAvailable:b.isAvailable!==false});ok(res,await product.populate('shopId','shopName'),'Product added');}catch(e){next(e)}}
module.exports={orders,shops,shopStatus,commission,settlements,processSettlements,deliveryPartners,products,createShop,createProduct};
