const Cart = require('../models/Cart');
const Product = require('../models/Product');
const { getPopulatedCart, validateCart } = require('../services/cartService');
const { ok } = require('../utils/responseHandler');
async function addItem(req, res, next) { try { const { productId, quantity = 1 } = req.body; const product = await Product.findById(productId); if (!product?.isAvailable) throw bad('Product unavailable'); if (quantity < 1 || quantity > product.stockQuantity) throw bad('Invalid quantity'); const price = product.offerPrice ?? product.price; let cart = await Cart.findOneAndUpdate({ customerId: req.user.id }, { $setOnInsert: { customerId: req.user.id } }, { upsert: true, new: true }); const existing = cart.items.find(i => String(i.productId) === String(productId)); if (existing) { if (existing.quantity + quantity > product.stockQuantity) throw bad('Quantity exceeds stock'); existing.quantity += quantity; existing.priceAtAddTime = price; } else cart.items.push({ productId, shopId: product.shopId, quantity, priceAtAddTime: price }); await cart.save(); ok(res, await getPopulatedCart(req.user.id), 'Added to cart', 201); } catch (e) { next(e); } }
async function getCart(req, res, next) { try { const cart = await getPopulatedCart(req.user.id); const groups = {}; for (const item of cart?.items || []) { const key = String(item.shopId?._id); groups[key] ||= { shop: item.shopId, items: [], subtotal: 0 }; groups[key].items.push(item); groups[key].subtotal += (item.productId?.offerPrice ?? item.productId?.price ?? item.priceAtAddTime) * item.quantity; } ok(res, { cartId: cart?._id, shops: Object.values(groups), pricingSummary: cart?.pricingSummary }); } catch (e) { next(e); } }
async function updateItem(req, res, next) { try { const cart = await Cart.findOne({ customerId: req.user.id }); const item = cart?.items.id(req.params.itemId); if (!item) throw Object.assign(new Error('Cart item not found'), { status: 404 }); const product = await Product.findById(item.productId); const quantity = Number(req.body.quantity); if (!Number.isInteger(quantity) || quantity < 1 || quantity > product.stockQuantity) throw bad('Invalid quantity'); item.quantity = quantity; await cart.save(); ok(res, cart); } catch (e) { next(e); } }
async function removeItem(req, res, next) { try { const cart = await Cart.findOne({ customerId: req.user.id }); const item = cart?.items.id(req.params.itemId); if (!item) throw Object.assign(new Error('Cart item not found'), { status: 404 }); item.deleteOne(); await cart.save(); ok(res, cart, 'Item removed'); } catch (e) { next(e); } }
async function validate(req, res, next) { try { const result = await validateCart(req.user.id, req.body.deliveryLocation); await Cart.updateOne({ customerId: req.user.id }, { deliveryLocation: result.deliveryLocation, pricingSummary: result.pricing }); ok(res, { shops: result.groups, pricing: result.pricing }, 'Cart is valid'); } catch (e) { next(e); } }
const bad = message => Object.assign(new Error(message), { status: 400 });
module.exports = { addItem, getCart, updateItem, removeItem, validate };
