const Product=require('../models/Product');const Shop=require('../models/Shop');const SubOrder=require('../models/SubOrder');const MasterOrder=require('../models/MasterOrder');const VendorSettlement=require('../models/VendorSettlement');const {ok}=require('../utils/responseHandler');
const transitions={pending:['accepted','rejected'],accepted:['preparing','cancelled'],preparing:['ready_for_pickup'],ready_for_pickup:[]};
async function orders(req,res,next){try{ok(res,await SubOrder.find({shopId:req.user.id}).sort({createdAt:-1}).populate('masterOrderId','orderNumber address paymentStatus'));}catch(e){next(e)}}
async function status(req,res,next){try{const order=await SubOrder.findOne({_id:req.params.subOrderId,shopId:req.user.id});if(!order)throw Object.assign(new Error('Order not found'),{status:404});if(!transitions[order.status]?.includes(req.body.status))throw Object.assign(new Error(`Cannot change ${order.status} to ${req.body.status}`),{status:409});order.status=req.body.status;if(req.body.estimatedPreparationTime)order.estimatedPreparationTime=req.body.estimatedPreparationTime;if(order.status==='rejected'){order.refundStatus='pending';await MasterOrder.updateOne({_id:order.masterOrderId},{$set:{paymentStatus:'partial_refund',masterStatus:'partially_cancelled'}});}await order.save();ok(res,order,'Status updated');}catch(e){next(e)}}
async function products(req,res,next){try{ok(res,await Product.find({shopId:req.user.id}).sort({createdAt:-1}));}catch(e){next(e)}}
async function createProduct(req,res,next){try{ok(res,await Product.create({...req.body,shopId:req.user.id}),'Product created',201);}catch(e){next(e)}}
async function updateProduct(req,res,next){try{const p=await Product.findOneAndUpdate({_id:req.params.productId,shopId:req.user.id},req.body,{new:true,runValidators:true});if(!p)throw Object.assign(new Error('Product not found'),{status:404});ok(res,p);}catch(e){next(e)}}
async function deleteProduct(req,res,next){try{const p=await Product.findOneAndDelete({_id:req.params.productId,shopId:req.user.id});if(!p)throw Object.assign(new Error('Product not found'),{status:404});ok(res,null,'Product deleted');}catch(e){next(e)}}
async function profile(req,res,next){try{const shop=await Shop.findById(req.user.id);if(!shop)throw Object.assign(new Error('Shop not found'),{status:404});ok(res,shop);}catch(e){next(e)}}
async function updateProfile(req,res,next){try{const allowed=['ownerName','shopName','shopType','email','address','location','deliveryRadiusKm','openingHours','minimumOrderValue','isOpen','fcmToken'];const patch=Object.fromEntries(Object.entries(req.body).filter(([key])=>allowed.includes(key)));const shop=await Shop.findByIdAndUpdate(req.user.id,patch,{new:true,runValidators:true});if(!shop)throw Object.assign(new Error('Shop not found'),{status:404});ok(res,shop,'Shop profile updated');}catch(e){next(e)}}
async function settlements(req,res,next){try{ok(res,await VendorSettlement.find({shopId:req.user.id}).sort({createdAt:-1}).populate('subOrderId'));}catch(e){next(e)}}
module.exports={orders,status,products,createProduct,updateProduct,deleteProduct,profile,updateProfile,settlements};
