function navAdmin(active){return `<div class="brand">FreshLane<small>Operations console</small></div><nav class="nav"><div class="nav-section">Overview</div><a class="${active==='dashboard'?'active':''}" href="admin-dashboard.html">Dashboard</a><a class="${active==='onboarding'?'active':''}" href="admin-onboarding.html">Easy onboarding</a><div class="nav-section">Marketplace</div><a class="${active==='shops'?'active':''}" href="admin-shops.html">Shops</a><a class="${active==='products'?'active':''}" href="admin-products.html">Products</a><a class="${active==='orders'?'active':''}" href="admin-orders.html">Orders</a><div class="nav-section">Operations</div><a class="${active==='delivery'?'active':''}" href="admin-delivery-partners.html">Delivery partners</a><a class="${active==='settlements'?'active':''}" href="admin-settlements.html">Settlements</a><a class="${active==='commission'?'active':''}" href="admin-commission-settings.html">Commissions</a></nav><div class="side-foot"><button class="btn ghost" style="width:100%" onclick="logout()">Sign out</button></div>`}
const setText=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value};

async function loadAdminDashboard(){const [orders,shops,settlements,riders]=await Promise.all([request('/admin/orders'),request('/admin/shops'),request('/admin/settlements'),request('/admin/delivery-partners')]);const gmv=orders.reduce((s,o)=>s+o.grandTotal,0),pendingShops=shops.filter(s=>s.status==='pending').length,pendingPayout=settlements.filter(s=>s.settlementStatus==='pending').reduce((a,s)=>a+s.payableAmount,0);setText('a-orders',orders.length);setText('a-gmv',money(gmv));setText('a-shops',shops.filter(s=>s.status==='approved').length);setText('a-payout',money(pendingPayout));setText('a-pending-shops',pendingShops);setText('a-riders',riders.filter(r=>r.isOnline).length);const recent=document.querySelector('#admin-recent-orders');if(recent)recent.innerHTML=orders.slice(0,6).map(o=>`<tr><td><strong>${o.orderNumber}</strong></td><td>${o.customerId?.name||'Customer'}</td><td>${money(o.grandTotal)}</td><td>${statusBadge(o.masterStatus)}</td><td>${new Date(o.createdAt).toLocaleDateString('en-IN')}</td></tr>`).join('')||emptyRow(5,'No orders yet')}

async function loadAdminOnboarding(){const [shops,products,orders]=await Promise.all([request('/admin/shops'),request('/admin/products'),request('/admin/orders')]);window.adminOnboardingShops=shops;setText('onboard-shops',shops.length);setText('onboard-products',products.length);setText('onboard-orders',orders.length);setText('onboard-pending',shops.filter(s=>s.status==='pending').length);const select=document.querySelector('#product-shop');if(select)select.innerHTML='<option value="">Select onboarded shop</option>'+shops.map(s=>`<option value="${s._id}">${s.shopName} - ${s.phone}</option>`).join('');const recent=document.querySelector('#onboard-recent-shops');if(recent)recent.innerHTML=shops.slice(0,5).map(s=>`<tr><td><strong>${s.shopName}</strong><br><small class="muted">${s.ownerName} - ${s.phone}</small></td><td>${s.shopType}</td><td>${s.address||'No address'}<br><small>${s.location?.latitude||''}, ${s.location?.longitude||''}</small></td><td>${statusBadge(s.status)}</td><td><a class="btn sm ghost" href="admin-products.html">View products</a></td></tr>`).join('')||emptyRow(5,'No shops onboarded yet')}
async function createAdminShop(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.latitude=Number(body.latitude);body.longitude=Number(body.longitude);body.deliveryRadiusKm=Number(body.deliveryRadiusKm||5);body.commissionPercentage=Number(body.commissionPercentage||10);try{const result=await request('/admin/shops',{method:'POST',body:JSON.stringify(body)});document.querySelector('#shop-create-message').innerHTML=`Vendor created. Login phone <strong>${result.credentials.phone}</strong>, password <strong>${result.credentials.password}</strong>`;e.target.reset();await loadAdminOnboarding()}catch(err){document.querySelector('#shop-create-message').textContent=err.message}}
async function createAdminProduct(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.price=Number(body.price);body.offerPrice=body.offerPrice?Number(body.offerPrice):undefined;body.stockQuantity=Number(body.stockQuantity||0);try{const product=await request('/admin/products',{method:'POST',body:JSON.stringify(body)});document.querySelector('#product-create-message').innerHTML=`Added <strong>${product.name}</strong> to ${product.shopId?.shopName||'shop'}.`;e.target.reset();await loadAdminOnboarding()}catch(err){document.querySelector('#product-create-message').textContent=err.message}}

async function loadAdminShops(){const data=await request('/admin/shops');window.adminShops=data;document.querySelector('tbody').innerHTML=data.map(s=>`<tr><td><strong>${s.shopName}</strong><br><small class="muted">${s.ownerName} - ${s.phone}</small></td><td>${s.shopType}</td><td>${s.address||'-'}<br><small>${s.location?.latitude?.toFixed(4)}, ${s.location?.longitude?.toFixed(4)}</small></td><td>${s.commissionPercentage}%</td><td>${statusBadge(s.status)} ${s.isOpen?'<span class="badge">open</span>':'<span class="badge danger">closed</span>'}</td><td><div class="actions"><button class="btn sm" onclick="adminShopStatus('${s._id}','approved')">Approve</button><button class="btn sm danger" onclick="adminShopStatus('${s._id}','suspended')">Suspend</button><button class="btn sm ghost" onclick="adminCommission('${s._id}',${s.commissionPercentage})">Commission</button></div></td></tr>`).join('')||emptyRow(6,'No shops')}
async function adminShopStatus(id,status){await request(`/admin/shops/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});loadAdminShops()}
async function adminCommission(id,current){const value=prompt('Commission percentage (0-100)',current);if(value===null)return;await request(`/admin/shops/${id}/commission`,{method:'PATCH',body:JSON.stringify({commissionPercentage:Number(value)})});loadAdminShops()}
async function loadAdminOrders(){const data=await request('/admin/orders');document.querySelector('tbody').innerHTML=data.map(o=>`<tr><td><strong>${o.orderNumber}</strong><br><small class="muted">${new Date(o.createdAt).toLocaleString('en-IN')}</small></td><td>${o.customerId?.name||'Customer'}<br><small>${o.customerId?.phone||''}</small></td><td>${o.subOrderIds?.length||0} shops</td><td>${money(o.grandTotal)}</td><td>${statusBadge(o.paymentStatus)}</td><td>${statusBadge(o.masterStatus)}</td></tr>`).join('')||emptyRow(6,'No orders')}
async function loadAdminProducts(){const data=await request('/admin/products');document.querySelector('tbody').innerHTML=data.map(p=>`<tr><td><div class="product-cell"><img class="product-thumb" src="${p.images?.[0]||'https://placehold.co/80x80?text=Item'}"><div><strong>${p.name}</strong><br><small>${p.category||''}</small></div></div></td><td>${p.shopId?.shopName||'-'}</td><td>${money(p.offerPrice??p.price)}</td><td>${p.stockQuantity} ${p.unit}</td><td>${p.isAvailable?'<span class="badge">Available</span>':'<span class="badge warn">Hidden</span>'}</td></tr>`).join('')||emptyRow(5,'No products')}
async function loadAdminSettlements(){const data=await request('/admin/settlements');window.adminSettlements=data;setText('admin-pending-payout',money(data.filter(x=>x.settlementStatus==='pending').reduce((s,x)=>s+x.payableAmount,0)));document.querySelector('tbody').innerHTML=data.map(s=>`<tr><td><input type="checkbox" class="settlement-check" value="${s._id}" ${s.settlementStatus!=='pending'?'disabled':''}></td><td>${s.shopId?.shopName||'-'}</td><td>${money(s.grossAmount)}</td><td>${money(s.commissionAmount)}</td><td><strong>${money(s.payableAmount)}</strong></td><td>${statusBadge(s.settlementStatus)}</td></tr>`).join('')||emptyRow(6,'No settlements')}
async function processSelectedSettlements(){const ids=[...document.querySelectorAll('.settlement-check:checked')].map(x=>x.value);if(!ids.length)return alert('Select at least one pending settlement.');await request('/admin/settlements/process',{method:'POST',body:JSON.stringify({settlementIds:ids})});loadAdminSettlements()}
async function loadAdminRiders(){const data=await request('/admin/delivery-partners');document.querySelector('tbody').innerHTML=data.map(r=>`<tr><td><strong>${r.name}</strong><br><small>${r.phone}</small></td><td>${r.vehicleType||'-'}</td><td>${r.isOnline?'<span class="badge">Online</span>':'<span class="badge warn">Offline</span>'}</td><td>${r.assignedOrders?.length||0}</td><td>${r.currentLocation?`${r.currentLocation.latitude}, ${r.currentLocation.longitude}`:'Not shared'}</td></tr>`).join('')||emptyRow(5,'No delivery partners')}
