const API=localStorage.apiBase||`${location.origin}/api`;
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.token}`,...options.headers}});const body=await r.json();if(!r.ok)throw new Error(body.message||'Request failed');return body.data}
async function login(role){const phone=document.querySelector('#phone').value,password=document.querySelector('#password').value;try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({phone,password,role})});localStorage.token=data.token;location.href=role==='admin'?'admin-dashboard.html':'vendor-dashboard.html'}catch(e){document.querySelector('.error').textContent=e.message}}
function logout(){localStorage.removeItem('token');location.href=location.pathname.includes('admin-')?'admin-login.html':'vendor-login.html'}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v||0)}
async function loadVendorOrders(){const data=await request('/vendor/orders');document.querySelector('tbody').innerHTML=data.map(o=>`<tr><td>${o.masterOrderId?.orderNumber||o._id}</td><td>${money(o.subtotal)}</td><td><span class="badge">${o.status}</span></td><td><select onchange="setStatus('${o._id}',this.value)"><option>Action</option><option>accepted</option><option>rejected</option><option>preparing</option><option>ready_for_pickup</option></select></td></tr>`).join('')}
async function setStatus(id,status){if(status==='Action')return;await request(`/vendor/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});loadVendorOrders()}
async function loadProducts(){const data=await request('/vendor/products');document.querySelector('tbody').innerHTML=data.map(p=>`<tr><td><div class="product-cell"><img class="product-thumb" src="${p.images?.[0]||'https://placehold.co/80x80?text=Item'}" alt=""><span>${p.name}</span></div></td><td>${p.unit}</td><td>${money(p.offerPrice??p.price)}</td><td>${p.stockQuantity}</td><td><span class="badge">${p.isAvailable?'Available':'Hidden'}</span></td></tr>`).join('')}
function previewProductImage(url){const img=document.querySelector('#image-preview');img.hidden=!url;if(url)img.src=url}
async function addProduct(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.price=+body.price;body.offerPrice=body.offerPrice?+body.offerPrice:undefined;body.stockQuantity=+body.stockQuantity;body.images=body.imageUrl?[body.imageUrl]:[];delete body.imageUrl;await request('/vendor/products',{method:'POST',body:JSON.stringify(body)});location.href='vendor-products.html'}
