const API=localStorage.apiBase||`${location.origin}/api`;
async function request(path,options={}){const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.token||''}`,...options.headers}});const body=await r.json();if(!r.ok){if(r.status===401&&!path.includes('/auth/'))localStorage.removeItem('token');throw new Error(body.message||'Request failed')}return body.data}
async function login(role){const phone=document.querySelector('#phone').value,password=document.querySelector('#password').value;try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({phone,password,role})});localStorage.token=data.token;localStorage.role=data.role;location.href=role==='admin'?'admin-dashboard.html':'vendor-dashboard.html'}catch(e){document.querySelector('.error').textContent=e.message}}
function logout(){const admin=location.pathname.includes('/admin/');localStorage.removeItem('token');localStorage.removeItem('role');location.href=admin?'admin-login.html':'vendor-login.html'}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v||0)}
function filterRows(value){document.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.innerText.toLowerCase().includes(value.toLowerCase()))}
function statusBadge(status){const bad=['rejected','cancelled','suspended','failed'].includes(status),warn=['pending','preparing','partial_refund'].includes(status);return `<span class="badge ${bad?'danger':warn?'warn':''}">${String(status||'unknown').replaceAll('_',' ')}</span>`}
function navVendor(active){return `<div class="brand">FreshLane<small>Vendor workspace</small></div><nav class="nav"><div class="nav-section">Manage</div><a class="${active==='dashboard'?'active':''}" href="vendor-dashboard.html">▦ Overview</a><a class="${active==='products'?'active':''}" href="vendor-products.html">□ Products</a><a class="${active==='orders'?'active':''}" href="vendor-orders.html">☷ Orders</a><a class="${active==='settlements'?'active':''}" href="vendor-settlements.html">₹ Settlements</a><div class="nav-section">Shop</div><a class="${active==='settings'?'active':''}" href="vendor-settings.html">⚙ Profile & location</a></nav><div class="side-foot"><button class="btn ghost" style="width:100%" onclick="logout()">Sign out</button></div>`}
async function loadVendorDashboard(){const [orders,products,profile,settlements]=await Promise.all([request('/vendor/orders'),request('/vendor/products'),request('/vendor/profile'),request('/vendor/settlements')]);const revenue=orders.filter(o=>o.status==='delivered').reduce((s,o)=>s+o.subtotal,0);const pending=orders.filter(o=>!['delivered','cancelled','rejected'].includes(o.status)).length;const payable=settlements.filter(s=>s.settlementStatus==='pending').reduce((a,s)=>a+s.payableAmount,0);document.querySelector('#shop-name').textContent=profile.shopName;document.querySelector('#shop-status').innerHTML=`${statusBadge(profile.status)} ${profile.isOpen?'<span class="badge">Open</span>':'<span class="badge danger">Closed</span>'}`;document.querySelector('#metric-orders').textContent=orders.length;document.querySelector('#metric-pending').textContent=pending;document.querySelector('#metric-revenue').textContent=money(revenue);document.querySelector('#metric-products').textContent=products.length;document.querySelector('#recent-orders').innerHTML=orders.slice(0,6).map(orderRow).join('')||emptyRow(5,'No orders yet');document.querySelector('#pending-payable').textContent=money(payable)}
function orderRow(o){return `<tr><td><strong>${o.masterOrderId?.orderNumber||String(o._id).slice(-8)}</strong></td><td>${o.items?.length||0} items</td><td>${money(o.subtotal)}</td><td>${statusBadge(o.status)}</td><td>${new Date(o.createdAt).toLocaleDateString('en-IN')}</td></tr>`}
async function loadVendorOrders(){const data=await request('/vendor/orders');window.vendorOrders=data;renderVendorOrders(data)}
function renderVendorOrders(data){document.querySelector('tbody').innerHTML=data.map(o=>`<tr><td><strong>${o.masterOrderId?.orderNumber||String(o._id).slice(-8)}</strong><br><small class="muted">${new Date(o.createdAt).toLocaleString('en-IN')}</small></td><td>${o.items?.map(i=>`${i.name} × ${i.quantity}`).join('<br>')||'—'}</td><td>${money(o.subtotal)}</td><td>${statusBadge(o.status)}</td><td><select class="status-select" onchange="setStatus('${o._id}',this.value)"><option value="">Update status</option>${availableStatuses(o.status).map(s=>`<option>${s}</option>`).join('')}</select></td></tr>`).join('')||emptyRow(5,'No orders found')}
const flow={pending:['accepted','rejected'],accepted:['preparing','cancelled'],preparing:['ready_for_pickup'],ready_for_pickup:[]};const availableStatuses=s=>flow[s]||[];
async function setStatus(id,status){if(!status)return;try{await request(`/vendor/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await loadVendorOrders()}catch(e){alert(e.message)}}
async function loadProducts(){const data=await request('/vendor/products');window.vendorProducts=data;renderProducts(data)}
function renderProducts(data){document.querySelector('tbody').innerHTML=data.map(p=>`<tr><td><div class="product-cell"><img class="product-thumb" src="${p.images?.[0]||'https://placehold.co/80x80?text=Item'}" alt=""><div><strong>${p.name}</strong><br><small class="muted">${p.category||'Uncategorised'}</small></div></div></td><td>${p.unit}</td><td>${money(p.offerPrice??p.price)}${p.offerPrice!=null?`<br><small class="muted">MRP ${money(p.price)}</small>`:''}</td><td>${p.stockQuantity}</td><td>${p.isAvailable?'<span class="badge">Available</span>':'<span class="badge warn">Hidden</span>'}</td><td><div class="actions"><button class="btn sm ghost" onclick="editProduct('${p._id}')">Edit</button><button class="btn sm ghost" onclick="toggleProduct('${p._id}',${!p.isAvailable})">${p.isAvailable?'Hide':'Show'}</button><button class="btn sm danger" onclick="deleteProduct('${p._id}')">Delete</button></div></td></tr>`).join('')||emptyRow(6,'No products yet')}
async function toggleProduct(id,isAvailable){await request(`/vendor/products/${id}`,{method:'PATCH',body:JSON.stringify({isAvailable})});loadProducts()}
async function deleteProduct(id){if(!confirm('Delete this product permanently?'))return;await request(`/vendor/products/${id}`,{method:'DELETE'});loadProducts()}
async function editProduct(id){const p=window.vendorProducts.find(x=>x._id===id);const price=prompt('Selling price',p.offerPrice??p.price);if(price===null)return;const stock=prompt('Stock quantity',p.stockQuantity);if(stock===null)return;await request(`/vendor/products/${id}`,{method:'PATCH',body:JSON.stringify({offerPrice:Number(price),stockQuantity:Number(stock)})});loadProducts()}
function previewProductImage(url){const img=document.querySelector('#image-preview');img.hidden=!url;if(url)img.src=url}
async function addProduct(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.price=+body.price;body.offerPrice=body.offerPrice?+body.offerPrice:undefined;body.stockQuantity=+body.stockQuantity;body.images=body.imageUrl?[body.imageUrl]:[];delete body.imageUrl;try{await request('/vendor/products',{method:'POST',body:JSON.stringify(body)});location.href='vendor-products.html'}catch(err){document.querySelector('.error').textContent=err.message}}
async function loadVendorSettlements(){const data=await request('/vendor/settlements');const total=data.reduce((s,x)=>s+x.payableAmount,0),pending=data.filter(x=>x.settlementStatus==='pending').reduce((s,x)=>s+x.payableAmount,0);document.querySelector('#settled-total').textContent=money(total-pending);document.querySelector('#pending-total').textContent=money(pending);document.querySelector('tbody').innerHTML=data.map(s=>`<tr><td>${String(s.subOrderId?._id||s.subOrderId).slice(-8)}</td><td>${money(s.grossAmount)}</td><td>${money(s.commissionAmount)}</td><td><strong>${money(s.payableAmount)}</strong></td><td>${statusBadge(s.settlementStatus)}</td><td>${s.settledAt?new Date(s.settledAt).toLocaleDateString('en-IN'):'—'}</td></tr>`).join('')||emptyRow(6,'No settlements yet')}
async function loadVendorProfile(){const p=await request('/vendor/profile');document.querySelector('#ownerName').value=p.ownerName||'';document.querySelector('#shopName').value=p.shopName||'';document.querySelector('#email').value=p.email||'';document.querySelector('#address').value=p.address||'';document.querySelector('#latitude').value=p.location?.latitude??'';document.querySelector('#longitude').value=p.location?.longitude??'';document.querySelector('#deliveryRadiusKm').value=p.deliveryRadiusKm||5;document.querySelector('#minimumOrderValue').value=p.minimumOrderValue||0;document.querySelector('#isOpen').value=String(p.isOpen)}
async function saveVendorProfile(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const body={ownerName:f.ownerName,shopName:f.shopName,email:f.email,address:f.address,location:{latitude:+f.latitude,longitude:+f.longitude},deliveryRadiusKm:+f.deliveryRadiusKm,minimumOrderValue:+f.minimumOrderValue,isOpen:f.isOpen==='true'};try{await request('/vendor/profile',{method:'PATCH',body:JSON.stringify(body)});document.querySelector('#save-message').textContent='Shop profile saved successfully.'}catch(err){document.querySelector('#save-message').textContent=err.message}}
const emptyRow=(cols,text)=>`<tr><td colspan="${cols}" class="empty-row">${text}</td></tr>`;
